### ISSUE TITLE
Error when installing tileserver-gl

### ISSUE THREAD

**Issue by nqlong** [klokantech/tileserver-gl#68]
Hi everyone, when I installed tileserver-gl. The error was in node-gyp rebuild. I try install pkg-config and ensure It was installed in /usr/bin/pkg-config. I used ubuntu 16.04.  Thank for any help.

```
> canvas@1.5.0 install /home/envi_hcmus/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/envi_hcmus/node_modules/canvas
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/envi_hcmus/package.json'
npm WARN envi_hcmus No description
npm WARN envi_hcmus No repository field.
npm WARN envi_hcmus No README data
npm WARN envi_hcmus No license field.
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "tileserver-gl"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/no
de-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/envi_hcmus/node_modules/canvas
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/envi_hcmus/package.j
son'
npm WARN envi_hcmus No description
npm WARN envi_hcmus No repository field.
npm WARN envi_hcmus No README data
npm WARN envi_hcmus No license field.
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "tileserver-gl"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! canvas@1.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/envi_hcmus/npm-debug.log 
```

**Comment by nqlong** [comment]
Hi, I have fixed the error. I let the information for anybody have same problem. I just removed the node_js package and used node_js package in local system, maybe it detected wrong node_js package. After that, I installed libcairo-dev. It solved my problem.

**Comment by Siliconrob** [comment]
Need more detail.  Having this same issue.  Manually installed libcairo-dev, but still nothing

**Comment by klokan** [comment]
Get the latest Docker at https://www.docker.com/products/docker-toolbox or at https://get.docker.com/ (for linux) and use the `klokantech/tileserver-gl` container prepared for docker.

Typical commands on any linux distro:
```
curl -sSL https://get.docker.com/ | sh
docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl
```

That's the easiest way how to deploy and test the TileServer-GL software.
Native deployment is possible of course - but then you have to solve the npm dependencies and ensure you have the correct version of the required binary libraries on your system. It means read the npm ERR logs and follow.

Node / npm gurus are welcome to make a pull request or comments here, on how to improve the native installation and make it easier.

**Comment by Siliconrob** [comment]
This answer **sucks**.  I think you should keep this open because it isn't solved.

**Comment by klokan** [comment]
I am sorry. Maybe @nqlong can provide you with more details?

Your comment did not mention any new information nor your error message - and @nqlong stated the problem was fixed for him and how.

I don't see an action which should be done on TileServer GL repository to improve the issue here. If you do, please let us know or create a pull request or new ticket.

**Comment by Siliconrob** [comment]
I was hoping for to compare the npm logs because he only provided the before log detail.  I will see if I can find the details and submit the log to him directly.  I did do what he said, but I was running Ubuntu 16.10 is the biggest difference.

**Comment by procogent** [comment]
We're running tileserver-gl on Ubuntu 16.10 without issue.  Here are the commands we used to get it running from a fresh install:

```
sudo apt-get install -y software-properties-common protobuf-compiler pkg-config libcairo2-dev libjpeg-dev libgif-dev git libgl1-mesa-glx build-essential g++ curl

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs xvfb

sudo mkdir /var/cache/npm
sudo npm config set cache /var/cache/npm --global

cd /tmp
git clone https://github.com/klokantech/tileserver-gl.git
cd tileserver-gl/

sudo npm install -g --unsafe-perm
```

**Comment by Siliconrob** [comment]
Thanks that helps

**Comment by klokan** [comment]
Thanks @procogent 

BTW the linux commands for installation on a fresh install of Debian 9.0 Stretch (now testing) are visible under https://github.com/klokantech/tileserver-gl/blob/master/Dockerfile

**Comment by rroset** [comment]
Something has changed since nov 2016, installation breaks at 
sudo npm install -g --unsafe-perm
> npm ERR! addLocal Could not install /tmp/tileserver-gl/plugins/tileshrink-gl

**Comment by petrsloup** [comment]
@rroset It is just a warning (*optional* dependency) and should not prevent the tileserver-gl from being successfully installed. I removed the `optionalDependencies` from `package.json` (it was related to experimentation with plugins) to prevent the warning in the future.

**Comment by rroset** [comment]
thanks @petrsloup
